---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Check existing certificate
  stat:
    path: /etc/letsencrypt/live/{{ letsencrypt_domains[0] }}/fullchain.pem
  register: le_cert

- name: Deploy nginx config (http-only or full)
  template:
    src: "{{ 'caliph_full.conf.j2' if le_cert.stat.exists else 'caliph_http.conf.j2' }}"
    dest: /etc/nginx/sites-available/caliph.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/caliph.conf
    dest: /etc/nginx/sites-enabled/caliph.conf
    state: link
  notify: Reload nginx

- name: Ensure nginx running
  service:
    name: nginx
    state: started
    enabled: yes
