name: Provision Infrastructure

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    paths:
      - 'ansible/**'
      - '.github/workflows/provision.yml'

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible & collections
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create inventory override (fixed host vps)
        run: |
          echo "[web]" > ansible/inventory/gha_host.ini
          grep -E "^vps(\s|$)" ansible/inventory/hosts.ini >> ansible/inventory/gha_host.ini || true
          cat ansible/inventory/gha_host.ini

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          BECOME_PASSWORD: ${{ secrets.BECOME_PASSWORD }}
        run: |
          cd ansible
          EXTRA_VARS="postgres_password=${POSTGRES_PASSWORD} target_host=vps"
          if [ -n "${BECOME_PASSWORD}" ]; then
            echo "Using become password from secret."
            EXTRA_VARS="$EXTRA_VARS ansible_become_pass=${BECOME_PASSWORD}"
          else
            echo "No BECOME_PASSWORD secret provided; assuming passwordless sudo (NOPASSWD) is configured."
          fi
          ansible-playbook -i inventory/hosts.ini site.yml -e "$EXTRA_VARS"

      - name: Finish
        run: echo "Provision finished"
